package com.iishanto.kikhabo.web.response;

public enum ErrorCodes {
    USER_ALREADY_EXISTS,
    INVALID_CREDENTIALS, SERVER_ERROR, UNAUTHORIZED_ACCESS, BAD_JSON, UNKNOWN_ERROR, FAILURE_CREATING_FAMILY_MEMBER, INVALID_ARGUMENTS
}
