package com.iishanto.kikhabo.infrastructure.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@Document(collection = "kikhabo-static-recipies")
public class RecipeDocument {

    @Id
    private String id;

    private String name;
    private String ingredients;
    private String url;
    private String image;
    private String source;
    private String recipeYield;
    private String datePublished;
    private String cookTime;
    private String prepTime;
    private String description;
    private String country;

    // Set to true once at startup for any recipe containing prohibited ingredients.
    // Used as a fast index-backed filter — avoids regex scanning on every query.
    private boolean excluded;

    // Generated by Gemini on first request, cached permanently.
    // null = not yet generated.
    private String cookingGuide;

}
