import 'dart:io';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';
import '../../data/models/meal.dart';

/// PDF Generator for shopping list
class ShoppingListPdfGenerator {
  /// Generates a PDF shopping list from meals
  /// Returns null if user cancels, otherwise returns the saved file
  static Future<File?> generateShoppingListPdf(List<Meal> meals) async {
    final pdf = pw.Document();
    
    // Load logo image
    final ByteData logoData = await rootBundle.load('assets/logo.png');
    final logoBytes = logoData.buffer.asUint8List();
    final logo = pw.MemoryImage(logoBytes);

    // Aggregate groceries
    final Map<String, int> groceries = {};
    for (var meal in meals) {
      for (var grocery in (meal.groceries ?? [])) {
        final amount = double.tryParse(grocery.amountInGm.trim())?.round() ?? 0;
        groceries[grocery.name] = (groceries[grocery.name] ?? 0) + amount;
      }
    }

    // Define colors matching app theme
    final primaryColor = PdfColor.fromHex('#047857'); // green-700
    final accentColor = PdfColor.fromHex('#F97316'); // orange-500
    final lightGreen = PdfColor.fromHex('#10B981'); // green-500

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Header with logo and branding
              _buildHeader(logo, primaryColor),
              pw.SizedBox(height: 32),

              // Title
              pw.Center(
                child: pw.Text(
                  'Shopping List',
                  style: pw.TextStyle(
                    fontSize: 28,
                    fontWeight: pw.FontWeight.bold,
                    color: primaryColor,
                  ),
                ),
              ),
              pw.SizedBox(height: 8),
              pw.Center(
                child: pw.Text(
                  'Kikhabo Meal Plan',
                  style: pw.TextStyle(
                    fontSize: 14,
                    color: lightGreen,
                  ),
                ),
              ),
              pw.SizedBox(height: 24),

              // Divider
              pw.Container(
                height: 2,
                color: primaryColor,
              ),
              pw.SizedBox(height: 24),

              // Groceries list
              ...groceries.entries.map((entry) => pw.Padding(
                padding: const pw.EdgeInsets.only(bottom: 12),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Expanded(
                      child: pw.Text(
                        '• ${entry.key}',
                        style: const pw.TextStyle(fontSize: 14),
                      ),
                    ),
                    pw.Container(
                      padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 4),
                      decoration: pw.BoxDecoration(
                        color: accentColor.shade(0.2),
                        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
                      ),
                      child: pw.Text(
                        '${entry.value}g',
                        style: pw.TextStyle(
                          fontSize: 13,
                          fontWeight: pw.FontWeight.bold,
                          color: accentColor,
                        ),
                      ),
                    ),
                  ],
                ),
              )),

              pw.Spacer(),

              // Footer
              pw.Container(
                height: 1,
                color: primaryColor,
              ),
              pw.SizedBox(height: 12),
              pw.Center(
                child: pw.Text(
                  'Generated by Kikhabo AI',
                  style: pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey600,
                    fontStyle: pw.FontStyle.italic,
                  ),
                ),
              ),
            ],
          );
        },
      ),
    );
    final pdfBytes = await pdf.save();

    // On Mobile (Android/iOS): Share the file which allows saving
    if (!kIsWeb && (Platform.isAndroid || Platform.isIOS)) {
      final directory = await getTemporaryDirectory();
      final fileName = 'shopping_list_${DateTime.now().millisecondsSinceEpoch}.pdf';
      final file = File('${directory.path}/$fileName');
      await file.writeAsBytes(pdfBytes);
      
      // Share allowing user to save/export
      await Share.shareXFiles(
        [XFile(file.path)], 
        text: 'Here is my shopping list from Kikhabo',
        subject: 'Shopping List'
      );
      
      return file;
    }

    // On Desktop: Use FilePicker to save
    final fileName = 'shopping_list_${DateTime.now().millisecondsSinceEpoch}.pdf';
    final String? outputPath = await FilePicker.platform.saveFile(
      dialogTitle: 'Save Shopping List PDF',
      fileName: fileName,
      type: FileType.custom,
      allowedExtensions: ['pdf'],
    );

    if (outputPath == null) {
      // User canceled the picker
      return null;
    }

    // Save PDF to chosen location
    final file = File(outputPath);
    await file.writeAsBytes(pdfBytes);

    return file;
  }

  /// Builds the header with logo and app name
  static pw.Widget _buildHeader(pw.MemoryImage logo, PdfColor primaryColor) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.center,
      children: [
        pw.Image(logo, width: 50, height: 50),
        pw.SizedBox(width: 16),
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              'Kikhabo',
              style: pw.TextStyle(
                fontSize: 28,
                fontWeight: pw.FontWeight.bold,
                color: primaryColor,
              ),
            ),
            pw.Text(
              'Your Meal Planning Assistant',
              style: pw.TextStyle(
                fontSize: 11,
                color: PdfColors.grey700,
              ),
            ),
          ],
        ),
      ],
    );
  }
}
